# Dependencies
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Carlos Chacin
tagline:             'Software Engineering Experiences'
description:         'Software Engineering experiences'
url:                 https://carloschac.in
baseurl:             ''
paginate:            5
excerpt_separator: "<!-- more -->"

sass:
  style: compressed

# About/contact
author:
  name:              Carlos Chacin
  url:               https://twitter.com/carloschacin
  email:             cchacin@gmail.com

# Twitter
twitter:
  username: CarlosChacin
  card: summary

# Social
social:
  name: Carlos Chacin
  links:
    - https://twitter.com/CarlosChacin
    - https://www.linkedin.com/in/CarlosChacin
    - https://github.com/cchacin

google_site_verification:

# Custom vars
version:             1.0.0
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
