# Dependencies
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-avatar

# Setup
title:               Learning Java/JavaEE
tagline:             'Blog about my Java/JavaEE experiences'
description:         'Blog about my Java/JavaEE experiences'
url:                 http://cchacin.github.io
baseurl:             ''
paginate:            5
excerpt_separator:   "<!-- more -->"

feed:
  categories:
    - java
    - javaee
    - jakartaee
    - microprofile
  excerpt_only: true

# About/contact
author:
  name:              Carlos Chacin
  url:               https://twitter.com/carloschacin
  email:             cchacin@gmail.com

# Custom vars
version:             1.0.0
